server:
  port: 8989
  
management:  endpoint:    gateway:      enabled: true
  endpoints:    web:      exposure:        include:        - gateway
        
  
spring:  application:    name: API-GATEWAY
  cloud:    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
                  routes:
      - id: ESTOCK-SERVICE
        uri: lb://ESTOCK-SERVICE
        predicates:
        - Path=/api/v/1.0/market/stock/** 
#        filters:
#       - AuthFilter
        
        
      - id: estock-stock-service
        uri: lb://CLAIM-SERVICE
        predicates:
        - Path=/api/v/1.0/market/stock/** 
      
             discovery:        locator:          lower-case-service-id: true
          enabled: true
    discovery:      enabled: true
       
eureka:  client:    register-with-eureka: true
    fetch-registry: true
    service-url:      defaultZone: http://localhost:8761/eureka/ 
  instance: 
    hostname: localhost
    
    
